language: java
sudo: false
jdk: oraclejdk8

script: 
 - "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

cache: 
 directories: 
 - '$HOME/.m2/repository' 
 - '$HOME/.sonar/cache'
