messenger:
  pageAccessToken: EAAVYyRyq4z8BAM9YBZAP3fOuykvX5Xzd6ZASPaTZC46MapqGLyZCRJHxo4vECqvcAkoEOnYIPHibM2fxhhXDAbZBkxx5cwN0MyAHMVCMXhdYZCA4sGNeBoH7zu8H2E3TcNxc8yZCmFWHXFtVMu9IrgyZCL1Hd6FQnMmBOeY8Nb078G3jyw24cZCYa
  appSecret: 8f44de54941a9ae9cf05608a4c6aa3bc
  verifyToken: token

management:
  port: 8081
  security:
    enabled: true

security:
  basic:
    enabled: false
  user:
    name: test
    password: test