messenger:
  pageAccessToken: EAAFPm2dotHsBAJVbUIaFwtekQ5A4zBCL5Kmrq8OFZC18di3qXyRvZCWSxiy3h1tUjnd4eiOM3Ht3L6F6uP4WbUUd1FpP7gVUVJMrj8WJdNi39aM1bGTc5HkDC75MrA0QBOuxfHMO9oenh7xZAMPjMaeZCqGHV8bAHBcRTAfPoAZDZD
  appSecret: bf00817292428306cb0c761941ad4d14
  verifyToken: token
  recommendation:
    products-amount: 3

logging:
    level:
        ROOT: INFO
        pl.hycom.pip: DEBUG
spring:
  datasource:
    url: jdbc:h2:file:~/db/h2test;
    username: test
    password: test
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /db-admin/console
