my:
  config:
    property:
      pageAccessToken: EAAImJ54xVrcBAJp5Aw1dU1zIPSw92mprMUo5QIRbux0WxrfKZCayfyEBJMmTJXoqrSfSglcUBV39YRvPZBo2jAaQu2QyiyA5vdTkCBbJE9NOAjpiM33PQ7sS0sIaMSsR6COd5IWihqYSjhTZBdQxfPqE7oliQ95lFKknSCUqQZDZD
      appSecret: d44fb500a9e69c572a8fa8d01fab8218
      verifyToken: token

management:
  port: 8081
  security:
    enabled: true
security:
  basic:
    enabled: true
  user:
    name: test
    password: test