messenger:
  pageAccessToken: EAAVYyRyq4z8BAM9YBZAP3fOuykvX5Xzd6ZASPaTZC46MapqGLyZCRJHxo4vECqvcAkoEOnYIPHibM2fxhhXDAbZBkxx5cwN0MyAHMVCMXhdYZCA4sGNeBoH7zu8H2E3TcNxc8yZCmFWHXFtVMu9IrgyZCL1Hd6FQnMmBOeY8Nb078G3jyw24cZCYa
  appSecret: 8f44de54941a9ae9cf05608a4c6aa3bc
  verifyToken: token

logging:
    level:
        ROOT: INFO
        pl.hycom.pip: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /db-admin/console