messenger:
  pageAccessToken: ${MESSENGER_PAGE_ACCESS_TOKEN}
  appSecret: ${MESSENGER_APP_SECRET}
  verifyToken: ${MESSENGER_VERIFY_TOKEN}
  host: mr-master.herokuapp.com
  port: 80
  protocol : http
  recommendation:
    products-amount: 3
  pipeline:
    filepath: /pipeline.xml

auth:
  login: admin@hycom.pl
  password: admin1

management:
  port: 8081

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update
  mail:
      host: smtp.gmail.com
      port: 587
      username: messenger.recommendations2017@gmail.com
      password: Admin_2017
      properties.mail.smtp:
            auth: true
            starttls.enable: true
            starttls.required: true