messenger:
  pageAccessToken: EAAFPm2dotHsBAJVbUIaFwtekQ5A4zBCL5Kmrq8OFZC18di3qXyRvZCWSxiy3h1tUjnd4eiOM3Ht3L6F6uP4WbUUd1FpP7gVUVJMrj8WJdNi39aM1bGTc5HkDC75MrA0QBOuxfHMO9oenh7xZAMPjMaeZCqGHV8bAHBcRTAfPoAZDZD
  appSecret: bf00817292428306cb0c761941ad4d14
  verifyToken: token

management:
  port: 8081
  security:
    enabled: true

security:
  basic:
    enabled: false
  user:
    name: test
    password: test
    
logging:
    level:
        ROOT: WARN
        pl.hycom.pip: DEBUG