messenger:
  pageAccessToken: ${MESSENGER_PAGE_ACCESS_TOKEN}
  appSecret: ${MESSENGER_APP_SECRET}
  verifyToken: ${MESSENGER_VERIFY_TOKEN}

management:
  port: 8081
  security:
    enabled: true

logging:
    level:
        ROOT: INFO
        pl.hycom.pip: DEBUG

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /db-admin/console